name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test 1
        run: echo "STEP 1 WORKING"

      - name: Test 2
        run: pwd

      - name: Test 3
        run: ls -la

      - name: Test 4
        run: bash --version

      - name: Test 5
        run: cat app.sh

      - name: Test 6
        run: bash app.sh

      - name: Test 7
        run: cat test.sh

      - name: Test 8
        run: bash test.sh
