name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Check file type
        run: file app.sh test.sh

      - name: Check shell
        run: bash --version

      - name: Run application
        run: bash app.sh

      - name: Run test
        run:  bash test.sh

